const KEY='jpc_v02';
let db=JSON.parse(localStorage.getItem(KEY)||'null')||{pin:null,pupils:[]};
const skills=['Moving off & stopping','Mirrors & signals','Junctions','Roundabouts','Parking','Independent driving','Dual carriageways'];
const labels={red:'Not introduced',orange:'Learning',yellow:'Almost test standard',green:'Test standard'};
function save(){localStorage.setItem(KEY,JSON.stringify(db))}
function esc(s=''){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function shell(title,body){document.getElementById('app').innerHTML=`<div class="app"><div class="top"><div class="brand">🚗 Just Passing</div><div class="sub">${title}</div></div><div class="content">${body}</div><div class="nav"><div class="navin"><button onclick="dashboard()">🏠<br>Home</button><button onclick="pupils()">👨‍🎓<br>Pupils</button><button onclick="showAdd()">➕<br>Add</button></div></div></div>`}
function render(){if(!db.pin){document.getElementById('app').innerHTML='<div class="app"><div class="top"><div class="brand">🚗 Just Passing</div><div class="sub">Companion v0.2</div></div><div class="content"><div class="card"><h2>Create your 4-digit PIN</h2><div class="field"><input id="pin" inputmode="numeric" maxlength="4" type="password" placeholder="4 digits"></div><button class="primary" onclick="setPin()">Continue</button></div></div></div>';return}dashboard()}
function setPin(){const p=document.getElementById('pin').value;if(!/^\d{4}$/.test(p))return alert('Please enter exactly 4 digits.');db.pin=p;save();dashboard()}
function dashboard(){const outstanding=db.pupils.reduce((a,p)=>a+(Number(p.balance)||0),0),today=new Date().toISOString().slice(0,10),lessons=db.pupils.flatMap(p=>(p.lessonsList||[]).filter(l=>l.date===today).map(l=>({...l,pupil:p.name})));shell('Companion',`<h2>Welcome 👋</h2><div class="grid"><div class="card"><div class="muted">Active pupils</div><div class="stat">${db.pupils.filter(p=>!p.passed).length}</div></div><div class="card"><div class="muted">Outstanding</div><div class="stat">£${outstanding.toFixed(2)}</div></div></div><div class="actions"><button class="primary" onclick="showAdd()">➕ Add Pupil</button><button class="dark" onclick="pupils()">👨‍🎓 Pupils</button></div><div class="card"><h3>Today's lessons</h3>${lessons.length?lessons.map(l=>`<div class="pupil lesson"><b>${esc(l.pupil)}</b><div class="muted">Lesson #${l.number} · ${esc(l.time||'')}</div></div>`).join(''):'<div class="muted">No lessons recorded today.</div>'}</div>`)}
function pupils(){const q=(prompt('Search pupils (leave blank for all):')||'').toLowerCase(),list=db.pupils.filter(p=>(p.name+' '+p.phone).toLowerCase().includes(q));shell('Pupils',`<div class="row"><h2>My Pupils</h2><button class="primary" onclick="showAdd()">Add</button></div><div class="list">${list.length?list.map(p=>`<div class="pupil" onclick="profile('${p.id}')"><div class="row"><div><strong>${esc(p.name)}</strong><span class="muted">${esc(p.phone||'No phone')} · ${(p.lessonsList||[]).length} lessons</span></div><span class="pill">${p.passed?'Passed':'£'+Number(p.balance||0).toFixed(2)}</span></div></div>`).join(''):'<div class="empty">No pupils yet.</div>'}</div>`)}
function showAdd(){shell('Add Pupil',`<button class="back" onclick="pupils()">← Back</button><h2>New Pupil</h2><div class="field"><label>Name</label><input id="name" placeholder="Full name"></div><div class="field"><label>Mobile</label><input id="phone" type="tel" placeholder="07..."></div><div class="field"><label>Email</label><input id="email" type="email"></div><div class="field"><label>Address</label><textarea id="address" rows="2"></textarea></div><div class="field"><label>Lesson price (£/hour)</label><input id="price" type="number" value="40"></div><div class="field"><label>Default lesson length</label><select id="duration"><option value="1">1 hour</option><option value="1.5">1½ hours</option><option value="2">2 hours</option></select></div><div class="field"><label>Notes</label><textarea id="notes" rows="3"></textarea></div><button class="primary" onclick="addPupil()">Save Pupil</button>`)}
function addPupil(){const name=document.getElementById('name').value.trim();if(!name)return alert('Please enter a name.');db.pupils.push({id:Date.now().toString(),name,phone:document.getElementById('phone').value.trim(),email:document.getElementById('email').value.trim(),address:document.getElementById('address').value.trim(),price:Number(document.getElementById('price').value)||40,duration:Number(document.getElementById('duration').value),notes:document.getElementById('notes').value.trim(),balance:0,passed:false,lessonsList:[],progress:Object.fromEntries(skills.map(s=>[s,'red']))});save();profile(db.pupils.at(-1).id)}
function profile(id){const p=db.pupils.find(x=>x.id===id);if(!p)return pupils();const lessons=p.lessonsList||[];shell('Pupil Profile',`<button class="back" onclick="pupils()">← Pupils</button><div class="card"><h2>${esc(p.name)}</h2><div class="actions"><a href="tel:${esc(p.phone)}"><button class="primary">📞 Call</button></a><a href="sms:${esc(p.phone)}"><button class="dark">💬 Text</button></a></div><p><b>Phone:</b> ${esc(p.phone)||'—'}</p><p><b>Lesson:</b> £${p.price}/hour · ${p.duration} hour${p.duration==1?'':'s'}</p><p><b>Balance:</b> £${Number(p.balance).toFixed(2)}</p></div><div class="actions"><button class="primary" onclick="newLesson('${id}')">🚗 Record Lesson</button><button class="dark" onclick="progress('${id}')">🚦 Progress</button></div><div class="card"><h3>Lesson history</h3>${lessons.length?lessons.slice().reverse().map(l=>`<div class="pupil lesson"><b>Lesson #${l.number}</b><div class="muted">${l.date} ${l.time||''} · ${l.duration}h · ${l.payment} · £${Number(l.amount||0).toFixed(2)}</div><div>${esc(l.notes||'')}</div></div>`).join(''):'<div class="muted">No lessons recorded yet.</div>'}</div><div class="actions"><button onclick="editPupil('${id}')">Edit</button><button class="danger" onclick="archivePupil('${id}')">${p.passed?'Restore pupil':'Move to Passed Pupils'}</button></div>`)}
function newLesson(id){const p=db.pupils.find(x=>x.id===id),next=(p.lessonsList||[]).length+1,today=new Date().toISOString().slice(0,10);shell('Record Lesson',`<button class="back" onclick="profile('${id}')">← Back</button><h2>Lesson #${next}</h2><div class="field"><label>Date</label><input id="date" type="date" value="${today}"></div><div class="field"><label>Time</label><input id="time" type="time"></div><div class="field"><label>Duration</label><select id="duration"><option value="1" ${p.duration==1?'selected':''}>1 hour</option><option value="1.5" ${p.duration==1.5?'selected':''}>1½ hours</option><option value="2" ${p.duration==2?'selected':''}>2 hours</option></select></div><div class="field"><label>Payment</label><select id="payment"><option>Paid - Cash</option><option>Paid - Bank transfer</option><option>Not paid</option></select></div><div class="field"><label>Amount (£)</label><input id="amount" type="number" value="${p.price*p.duration}"></div><div class="field"><label>Lesson notes</label><textarea id="notes" rows="4" placeholder="What did you work on?"></textarea></div><button class="primary" onclick="saveLesson('${id}')">Save Lesson #${next}</button>`)}
function saveLesson(id){const p=db.pupils.find(x=>x.id===id),l={number:(p.lessonsList||[]).length+1,date:document.getElementById('date').value,time:document.getElementById('time').value,duration:Number(document.getElementById('duration').value),payment:document.getElementById('payment').value,amount:Number(document.getElementById('amount').value)||0,notes:document.getElementById('notes').value.trim()};p.lessonsList=p.lessonsList||[];p.lessonsList.push(l);if(l.payment==='Not paid')p.balance=(Number(p.balance)||0)+l.amount;save();profile(id)}
function progress(id){const p=db.pupils.find(x=>x.id===id);p.progress=p.progress||Object.fromEntries(skills.map(s=>[s,'red']));shell('Progress',`<button class="back" onclick="profile('${id}')">← Back</button><h2>🚦 ${esc(p.name)}</h2><div class="card">${skills.map(s=>`<div class="progress-item"><b>${esc(s)}</b><div class="rating">${['red','orange','yellow','green'].map(c=>`<button class="${p.progress[s]===c?'sel':''}" onclick="setProgress('${id}','${s}','${c}')">${c==='red'?'🔴':c==='orange'?'🟠':c==='yellow'?'🟡':'🟢'}</button>`).join('')}</div><div class="small muted">${labels[p.progress[s]]}</div></div>`).join('')}</div>`)}
function setProgress(id,s,c){const p=db.pupils.find(x=>x.id===id);p.progress=p.progress||{};p.progress[s]=c;save();progress(id)}
function archivePupil(id){const p=db.pupils.find(x=>x.id===id);p.passed=!p.passed;save();profile(id)}
function editPupil(id){const p=db.pupils.find(x=>x.id===id);shell('Edit Pupil',`<button class="back" onclick="profile('${id}')">← Back</button><h2>Edit ${esc(p.name)}</h2><div class="field"><label>Name</label><input id="name" value="${esc(p.name)}"></div><div class="field"><label>Mobile</label><input id="phone" value="${esc(p.phone)}"></div><div class="field"><label>Lesson price</label><input id="price" type="number" value="${p.price}"></div><div class="field"><label>Lesson length</label><select id="duration"><option value="1" ${p.duration==1?'selected':''}>1 hour</option><option value="1.5" ${p.duration==1.5?'selected':''}>1½ hours</option><option value="2" ${p.duration==2?'selected':''}>2 hours</option></select></div><div class="field"><label>Notes</label><textarea id="notes">${esc(p.notes)}</textarea></div><button class="primary" onclick="updatePupil('${id}')">Save Changes</button>`)}
function updatePupil(id){const p=db.pupils.find(x=>x.id===id);p.name=document.getElementById('name').value.trim();p.phone=document.getElementById('phone').value.trim();p.price=Number(document.getElementById('price').value)||40;p.duration=Number(document.getElementById('duration').value);p.notes=document.getElementById('notes').value.trim();save();profile(id)}
render();